version: "2"

services:
    dev:
        ports:
            - "8000:80"
        extends:
            service: wordpress
    prod:
        ports:
            - "80:80"
        extends:
            service: wordpress
    wordpress:
        build: wordpress
        volumes:
            - "./backup:/backup"
