version: "2"

services:
    dev:
        ports:
            - "8000:80"
        extends:
            service: wordpress
        environment:
            - "SERVICE_NAME=dev"
        volumes:
            - "./backup/dev:/usr/share/wordpress"
    prod:
        ports:
            - "80:80"
        extends:
            service: wordpress
        environment:
            - "SERVICE_NAME=prod"
        volumes:
            - "./backup/prod:/usr/share/wordpress"
    wordpress:
        build: wordpress
        volumes:
            - "./backup:/backup"
